### ISSUE TITLE
SetUp

### ISSUE THREAD

**Issue by tlharding5996** [Tommrodrigues/homebridge-web-thermostat#10]
I'm new to coding so not familiar with some of these things... how would I go about finding the apiroute (http://myurl.com) for the thermostat? Would this pluggin work with an Aprilaire WiFi thermostat?

**Comment by phenotypic** [comment]
The `apiroute` is simply the address of the device you are trying to connect to. For a local device it might be something like `192.168.1.56`. Whatever the address, the device should be capable of handling the API requirements specified in the `README.md`.

This plugin is not designed to work with the thermostat you have described. Your best chance for integrating this thermostat to homebridge would be to look for a plugin specific to this model, or to create a new plugin designed around the API requirements of your thermostat.
