### ISSUE TITLE
group thermostats in home app

### ISSUE THREAD

**Issue by satrik** [Tommrodrigues/homebridge-web-thermostat#11]
Hi,

I'm wondering why it isn't possible to group multiple thermostats from the same room in the home app. 
Isn't it possible with your plugin or am I missing anything?

Greetings
satrik

**Comment by phenotypic** [comment]
Hi there, this feature is not implemented as part of the plugin. 

Other devices like lights and smart plugs can be grouped from within the Home app, so it may be possible to do the same thing with multiple thermostats. However, this isn't something I have tried before, though you can set up automations for multiple thermostat devices from the automations pane within the app.
