### ISSUE TITLE
setTargetHeatingCoolingState() sets current instead of target heating state

### ISSUE THREAD

**Issue by Eddy-the-Git** [Tommrodrigues/homebridge-web-thermostat#12]
Line 161:

`this.service.getCharacteristic(Characteristic.CurrentHeatingCoolingState).updateValue(value)`

should update the `Characteristic.TargetHeatingCoolingState` value like it advertises in line 160:

`this.log('Set targetHeatingCoolingState to: %s', value)`

**Comment by phenotypic** [comment]
Good suggestion, but I feel this will be better solved with a change to a `_getStatus` function call instead after any `target` API calls. See your other issue #13 for more details.
