### ISSUE TITLE
Feature Request: Call _getStatus after setting changes via API

### ISSUE THREAD

**Issue by Eddy-the-Git** [Tommrodrigues/homebridge-web-thermostat#13]
The HomeKit thermostat UIs would be a lot snappier (not having to wait for the next poll for updates) if 

`_getStatus`

was called after these API calls are finished:

`/targetHeatingCoolingState
/targetTemperature
/coolingThresholdTemperature
/heatingThresholdTemperature`

**Comment by phenotypic** [comment]
Hi there, I like your suggestion and think it could solve the other issue you opened (#12).

However, correct me if I'm wrong, but this would only be useful for `target` API calls (e.g. `/targetHeatingCoolingState`), as the API's value for `/coolingThresholdTemperature` for example, should not differ from the call if it was successful.

Running a `_getStatus` after a `target` call would mean we don't need to call a `this.service.getCharacteristic` to update the UI.

Please feel free to open a pull request replacing the `this.service.getCharacteristic` lines for each of the `target` calls with a `_getStatus` function call after completing testing. I'll look to do this myself some time in the future when I have some spare time if not.

**Comment by phenotypic** [comment]
Hi there, your suggestion has been integrated in the latest release of this plugin.

I have resolved the issue be replacing `this.service.getCharacteristic` with an API call once the `HeatingCoolingState` has been updated by the user (9b376b1).
