### ISSUE TITLE
pass temp setting ?

### ISSUE THREAD

**Issue by boscorelly** [Tommrodrigues/homebridge-web-thermostat#14]
Hi,

i tried to use your plugin with Domoticz to setup a thermostat temperature. Settings can be set by passing them to the url

i want to know if it is possible to send the thermostat selected temp through the url ?

url is like this : http://192.168.1.55:8080/json.htm?type=command&param=switchlight&idx=104&switchcmd=Set%20Level&level=20

20 is the temp desired.

**Comment by phenotypic** [comment]
Hi there, you can see the API expectations in the README. This plugin does not contain native support for Domoticz, so it may be better to find one that does. Alternatively, you could fork this repository and change instances of the API calls to fit with your requirements.
