### ISSUE TITLE
Modify Plugin

### ISSUE THREAD

**Issue by frizby66** [Tommrodrigues/homebridge-web-thermostat#18]
Know its not an issue, more of a challenge...looking to try and modify this plugin to connect to a wifi enable hot tub. Have details of the structure, commands and api calls needed to read status and issue commands...just not sure how to achieve it!

**Comment by phenotypic** [comment]
Hi there, you would almost certainly be able to modify this plugin to control the thermostat of a Wi-Fi enabled hot tub to some extent.

Unfortunately, I don't have the time or incentive to implement this myself. You are more than welcome to fork the plugin and attempt this yourself though!
