### ISSUE TITLE
RegEx patterns

### ISSUE THREAD

**Issue by ixy05** [Tommrodrigues/homebridge-web-thermostat#19]
Hello, 

Great work on the plugin!
It would be cool if the URLs that are used for data collection could have their own custom RegEx patterns with them. This would then allow there to be more flexibility with where the data comes from so it doesn't need to conform to current constraints when /status is called.

Thanks!

**Comment by phenotypic** [comment]
Hi there, this is something that would certainly be possible, though it would likely have to be specific for the intended data source.

Unfortunately, I don't have the time or incentive to implement this myself. You are more than welcome to fork the plugin and attempt this yourself though!

**Comment by GevaudanBeast** [comment]
@ixy05 hello, do you find a way ?
