### ISSUE TITLE
Wrong thresholds temperature range

### ISSUE THREAD

**Issue by augustozanellato** [Tommrodrigues/homebridge-web-thermostat#2]
Even if i set maxTemp and minTemp in config.json when I'm in auto mode the range is 0°-35°

My config.json
```
     {
       "accessory": "Thermostat",
       "name": "Thermostat",
       "apiroute": "http://192.168.1.252",
       "currentRelativeHumidity": true,
       "minTemp": 16,
       "maxTemp": 30,
       "pollInterval": 60,
       "manufacturer": "Samsung",
       "model": "AR07FSFPESNN",
       "firmware" : "v1.0.0",
       "temperatureThresholds": true
     }
```

**Comment by phenotypic** [comment]
Hi there,

`maxTemp` and `minTemp` do not define the temperature thresholds. If you look in the README, you'll see that they define the upper and lower bounds for the temperature selector.

If you look at the section of the README labelled `API Interfacing`, it says that your API should return `coolingThresholdTemperature` and `heatingThresholdTemperature` when `temperatureThresholds` is `true`. Could you please verify that you are returning these two JSON fields when `/status` is requested?

**Comment by augustozanellato** [comment]
Ok, but the problem is that when I go in auto mode the temp range is 0~35° even if I set minTemp and maxTemp in config.json.
Example: in home app I can set auto mode with 0-10° thresholds, but that doesn’t make any sense because my minTemp is 16°

**Comment by phenotypic** [comment]
Ah, I think I understand what you're saying. Your problem isn't with the `coolingThresholdTemperature` and `heatingThresholdTemperature` it's with the entire temperature range when you're in `Auto` mode? I.e. when you are in `Off`/`Heat`/`Cool` mode the temperature range is correct, it's only 0-35° when you are in `Auto` mode?

If so, i'm afraid this is a feature of the Home app and there is nothing that can be done to fix this as far as the plugin is concerned.

Could you verify that what I have described is what you are describing and that there are no negative functional implications as a result of what is described above?

**Comment by augustozanellato** [comment]
Yeah, that’s definitely the issue. There aren’t any other negative implications.

**Comment by augustozanellato** [comment]
It's not a bug in Home app, check PR #4

**Comment by phenotypic** [comment]
Good find, hadn't thought to set bounds on the heating and cooling thresholds but it makes sense. I'll merge your pull request now

**Comment by augustozanellato** [comment]
Just FYI, when a pr is marked as “fixes #...” you don’t need to close the issue manually, it gets closed automatically by github when the PR is merged to master, see [here](https://help.github.com/en/articles/closing-issues-using-keywords)
