### ISSUE TITLE
TargetHeatingCoolingState cannot be set to AUTO 

### ISSUE THREAD

**Issue by mariusz2108** [Tommrodrigues/homebridge-web-thermostat#20]
When changing TargetHeatingCooling state to AUTO home bridge returns error.
That's because updated is CurrentHeatingCoolingState (AUTO for this does not make any sens).
I think CurrentHeatingCoolingState should be changed to TargetHeatingCoolingState

**Comment by phenotypic** [comment]
Hi there, thank you for opening this issue!

You are correct that `AUTO` is an invalid property for `CurrentHeatingCoolingState`, and should only be applied to `TargetHeatingCoolingState`.

In the latest release I have resolved the issue by replacing `this.service.getCharacteristic` with an API call once the `HeatingCoolingState` has been updated by the user (9b376b1e4bca4ddb19aa289e0025ad03028bba60).
