### ISSUE TITLE
Min/Max Values Do not apply to current temperature

### ISSUE THREAD

**Issue by JakeAi** [Tommrodrigues/homebridge-web-thermostat#22]
Hello, I use this plugin to automate my wood stove. You allow the temperature thresholds to be changed, but once it passes 212*F (100*C) it errors out because there is an internal limit in the Characteristic.CurrentTemperature. I forked it awhile ago and added (below) but I don't want to keep updating my fork with your updates. Is this plausible to add the min/max for current temperature as well?

```JS
    this.service
      .getCharacteristic(Characteristic.CurrentTemperature)
      .setProps({
        minValue: -600,
        maxValue: 600
      });
```

**Comment by phenotypic** [comment]
Hi there, according to the [Homebridge API reference for `CurrentTemperature`](https://developers.homebridge.io/#/characteristic/CurrentTemperature), the minimum and maximum values allowed for the characteristic are `-270` and `100` respectively.

The plugin does not interfere with these boundaries. Are you able to confirm that your fork allows you to set values past this range?

**Comment by JakeAi** [comment]
@Tommrodrigues Here is a screenshot of the widget surpassing the 212F / 100C limitation. 
https://imgur.com/a/gsExuih

**Comment by phenotypic** [comment]
That's interesting, I'm surprised that you were able to surpass the limitation imposed by Homebridge.

I have integrated your request into the latest release (commit 770468de6cab7a47f3a1db8c3d928e35809e1396). Thank you for your request!
