### ISSUE TITLE
Does this work with Baxi?

### ISSUE THREAD

**Issue by miguelpruivo** [Tommrodrigues/homebridge-web-thermostat#25]
Hi!

Sorry if this is sort of a dumb question but: does this work with BAXI heaters? I have a BAXI heater with a wireless thermostat (RXM) but I can't figure a way to integrate with homebridge. I know it has opentherm and it uses its property bridge to communicate with the wireless thermostat (RF).

Is there anything else I can do?

Thanks!

**Comment by phenotypic** [comment]
Hi there, this plugin is not designed to work with any specific brand of heater/thermostat. Instead, it communicates with an API using the HTTP calls specified in [API Interfacing](https://github.com/phenotypic/homebridge-web-thermostat#api-interfacing).

Feel free to fork the plugin and modify these HTTP calls to work with your heater. Alternatively, take a look at [homebridge-web-boiler](https://github.com/phenotypic/homebridge-web-boiler/tree/master/examples) to see how you can make your own homebridge-compatible OpenTherm bridge.
