### ISSUE TITLE
Status delay

### ISSUE THREAD

**Issue by FunnyDevs** [Tommrodrigues/homebridge-web-thermostat#26]
Hello!
Could it be possibile to have a delay configuration for /status endpoint?
I have 4 ble thermostats and i would like to have a same poll interval but a starting delay between each other.
So, for example
*thermostat 1 call /status at time 0 with pollinterval 20 seconds
*thermostat 2 call /status at time 5 with pollinterval 20 seconds
*thermostat 3 call /status at time 10 with pollinterval 20 seconds
*thermostat 4 call /status at time 15 with pollinterval 20 seconds

**Comment by phenotypic** [comment]
Hi there, this is not something currently supported by this plugin. However, you can set different poll intervals for each of your thermostats which would likely achieve the same result.
