### ISSUE TITLE
Fan support

### ISSUE THREAD

**Issue by augustozanellato** [Tommrodrigues/homebridge-web-thermostat#3]
What about adding fan control support similar to this zoltanhosszu/homebridge-web-thermostat.
It's a fork of your project, but I think you could pull in that changes and make the fan control section optional.

**Comment by phenotypic** [comment]
That fork does not expose a `Thermostat` service as my plugin does. Instead, it exposes a `HeaterCooler` service. 

Please look at the [HomeKit specification](https://developer.apple.com/homekit/specification/), you will see that under the `Thermostat` service there are no characteristics that can be exposed relating to fan control and thus there is nothing I can do to this plugin to add the functionality you are describing.

As for the `HeaterCooler` service, you can see that there are indeed characteristics that relate to fan control. However, my plugin serves my needs and I have no incentive / extra free time at the moment to develop a `HeaterCooler` plugin from scratch. Of course, you are more than welcome to create your own plugin which exposes your desired characteristics.
