### ISSUE TITLE
Salus it500

### ISSUE THREAD

**Issue by Vaoske** [Tommrodrigues/homebridge-web-thermostat#5]
Hi,
Is there any possibility your homebridge plug-in will works with an Salus It500?
The website to connect my Thermostat is https://salus-it500.com/public/login.php?lang=nl

Greets form The Netherlands
Remko Faes

**Comment by phenotypic** [comment]
The API specification defined by this plugin can be seen in the `README.md`

I doubt this plugin will work with your thermostat, and I have neither the time or the incentive to work on integrating functionality with this specific device

Google is your friend, searching `homebridge salus It500` yields [this](https://github.com/louy/homebridge-salus-it500) as the first result - I'd suggest starting there

Best,
Tom
