### ISSUE TITLE
new minStep option vs. displayed values

### ISSUE THREAD

**Issue by G0sch** [Tommrodrigues/homebridge-web-thermostat#8]
Hi

I tested the new minStep option with 0.2 - in the Home App the steps for the targetTemp are still 0.5.
(Homebridge log shows 0.2 steps)
Is there some Characteristics Settings missing?

**Comment by phenotypic** [comment]
Hi there, this is a known issue/feature of the Home App. The finest resolution that the app will recognise is still 0.5, even if you set it lower. I believe that other HomeKit apps might recognise resolutions finer than 0.5. Maybe in the future Apple will issue an update that allows for finer resolution natively within the Home app.

**Comment by G0sch** [comment]
thx for the fast reply. is it possible to show the currentTemp with an finer resolution? (0.2 or 0.1)

**Comment by phenotypic** [comment]
Unfortunately not, the issue is once again with the Home app. I think other apps will display the temperature with a finer resolution.

**Comment by G0sch** [comment]
ah sorry... i read over your first answer too fast and mixed home app <> homekit.
You are right: Eve and Home+ show the temps with fine scaling
thank you!
